-- Create expenses table
create table if not exists public.expenses (
  id bigint generated always as identity primary key,
  title text not null,
  amount numeric(12, 2) not null check (amount > 0),
  spent_on date not null,
  created_at timestamptz not null default now()
);

alter table public.expenses enable row level security;

-- Public demo policy (replace with authenticated policies for production apps)
create policy "allow public read"
  on public.expenses
  for select
  to anon
  using (true);

create policy "allow public insert"
  on public.expenses
  for insert
  to anon
  with check (true);

create policy "allow public delete"
  on public.expenses
  for delete
  to anon
  using (true);
-- Run this in Supabase SQL editor.

create table if not exists public.income_entries (
  id bigint generated by default as identity primary key,
  user_id text not null,
  month_key text not null,
  name text not null,
  amount numeric not null,
  status text not null,
  origin_id text,
  rolled_from text,
  created_at timestamptz not null default now()
);

create table if not exists public.expense_entries (
  id bigint generated by default as identity primary key,
  user_id text not null,
  month_key text not null,
  name text not null,
  amount numeric not null,
  category text not null,
  created_at timestamptz not null default now()
);

create table if not exists public.recurring_entries (
  id bigint generated by default as identity primary key,
  user_id text not null,
  freq text not null,
  name text not null,
  amount numeric not null,
  category text not null,
  start_key text not null,
  month_for_yearly int,
  created_at timestamptz not null default now()
);

alter table public.income_entries enable row level security;
alter table public.expense_entries enable row level security;
alter table public.recurring_entries enable row level security;

-- Demo policy for shared app user id model.
drop policy if exists "income_entries_user_filter" on public.income_entries;
create policy "income_entries_user_filter"
  on public.income_entries
  for all
  using (user_id = 'shared-user')
  with check (user_id = 'shared-user');

drop policy if exists "expense_entries_user_filter" on public.expense_entries;
create policy "expense_entries_user_filter"
  on public.expense_entries
  for all
  using (user_id = 'shared-user')
  with check (user_id = 'shared-user');

drop policy if exists "recurring_entries_user_filter" on public.recurring_entries;
create policy "recurring_entries_user_filter"
  on public.recurring_entries
  for all
  using (user_id = 'shared-user')
  with check (user_id = 'shared-user');
