-- Run this in Supabase SQL editor.

create table if not exists public.income_entries (
  id bigint generated by default as identity primary key,
  user_id text not null,
  month_key text not null,
  name text not null,
  amount numeric not null,
  status text not null,
  origin_id text,
  rolled_from text,
  created_at timestamptz not null default now()
);

create table if not exists public.expense_entries (
  id bigint generated by default as identity primary key,
  user_id text not null,
  month_key text not null,
  name text not null,
  amount numeric not null,
  category text not null,
  created_at timestamptz not null default now()
);

create table if not exists public.recurring_entries (
  id bigint generated by default as identity primary key,
  user_id text not null,
  freq text not null,
  name text not null,
  amount numeric not null,
  category text not null,
  start_key text not null,
  month_for_yearly int,
  created_at timestamptz not null default now()
);

alter table public.income_entries enable row level security;
alter table public.expense_entries enable row level security;
alter table public.recurring_entries enable row level security;

-- Demo policy for shared app user id model.
drop policy if exists "income_entries_user_filter" on public.income_entries;
create policy "income_entries_user_filter"
  on public.income_entries
  for all
  using (user_id = 'shared-user')
  with check (user_id = 'shared-user');

drop policy if exists "expense_entries_user_filter" on public.expense_entries;
create policy "expense_entries_user_filter"
  on public.expense_entries
  for all
  using (user_id = 'shared-user')
  with check (user_id = 'shared-user');

drop policy if exists "recurring_entries_user_filter" on public.recurring_entries;
create policy "recurring_entries_user_filter"
  on public.recurring_entries
  for all
  using (user_id = 'shared-user')
  with check (user_id = 'shared-user');
